### ISSUE TITLE
Call to video_blend.py Fails to Handle Spaces in File Paths Correctly

### ISSUE THREAD

**Issue by rogerb831** [ashleykleynhans/rerender-a-video-docker#1]
When the video_blend.py script is called with file paths that contain spaces, the program fails to recognize the arguments and throws a FileNotFoundError.

### Environment
- **Python version**: 3.10.12
- **Operating System**: Linux Studio 5.15.90.1-microsoft-standard-WSL2 (Running on WSL2)
- **Docker version**: 24.0.6, build ed223bc
- **Commit SHA**: a348e0a549f3856e58fe610b52eecb4972d1c992

Example:
`python video_blend.py result/production_id_4695825 1080p --beg 1 --end 1041 --itv 10 --key keys  --output result/production_id_4695825 1080p/blend.mp4 --fps 50.0 --n_proc 4 -ps
usage: video_blend.py [-h] [--output OUTPUT] [--fps FPS] [--beg BEG] [--end END] [--itv ITV] [--key KEY]
                      [--n_proc N_PROC] [-ps] [-ne] [-tmp]
                      name
video_blend.py: error: unrecognized arguments: 1080p 1080p/blend.mp4
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'result/production_id_4695825 1080p/blend.mp4'`

**Comment by ashleykleynhans** [comment]
Wrong repo, this is just a Docker image.

https://github.com/williamyang1991/Rerender_A_Video
